name: Update Ngrok Address in index.html

on:
  workflow_dispatch:

jobs:
  update-address:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ngrok
        run: |
          wget -q -O ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip -q ngrok.zip
          chmod +x ngrok
          ./ngrok authtoken ${{ secrets.NGROK_TOKEN }}  

      - name: Start ngrok
        id: start-ngrok
        run: |
          ./ngrok http 37799 &  # 替换为你的实际端口
          sleep 5

      - name: Get ngrok address
        id: get-address
        run: |
          NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "ngrok_url=$NGROK_URL" >> $GITHUB_OUTPUT

      - name: Update index.html
        run: |
          sed -i "s|https://{{NGROK_ADDRESS}}|${{ steps.get-address.outputs.ngrok_url }}|g" index.html

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 无需修改，保持默认
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.html
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update ngrok address to ${{ steps.get-address.outputs.ngrok_url }}"
            git push
          fi
