name: Update Ngrok Address in index.html

on:
  # 这里设置为手动触发，你也可以根据需求设置为定时触发
  workflow_dispatch:

jobs:
  update-address:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract ngrok
        run: |
          Expand-Archive -Path ngrok-v3-stable-windows-amd64.zip -DestinationPath .
          .\ngrok.exe authtoken ${{ secrets.NGROK_TOKEN }}

      - name: Start ngrok
        id: start-ngrok
        run: |
          Start-Process -FilePath .\ngrok.exe -ArgumentList "http 37799"
          Start-Sleep -Seconds 5

      - name: Get ngrok address
        id: get-address
        run: |
          $NGROK_URL = (Invoke-RestMethod -Uri http://localhost:4040/api/tunnels).tunnels[0].public_url
          echo "ngrok_url=$NGROK_URL" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Update index.html
        run: |
          $content = Get-Content -Path index.html
          $newContent = $content -replace "https://{{NGROK_ADDRESS}}", "${{ steps.get-address.outputs.ngrok_url }}"
          $newContent | Set-Content -Path index.html

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.html
          if (-not (git diff --quiet)) {
            git commit -m "Update ngrok address in index.html to ${{ steps.get-address.outputs.ngrok_url }}"
            git push
          } else {
            echo "No changes to commit"
          }    
