name: Update Ngrok Address in index.html

on:
  # 手动触发
  workflow_dispatch:
  # 定时触发，这里设置为每小时触发一次，你可以根据需要调整
  schedule:
    - cron: '0 * * * *'

jobs:
  update-address:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get ngrok address
        id: get-address
        run: |
          try {
            $NGROK_URL = (Invoke-RestMethod -Uri http://localhost:4040/api/tunnels).tunnels[0].public_url
            echo "ngrok_url=$NGROK_URL" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          }
          catch {
            Write-Error "Failed to get ngrok address: $_"
            exit 1
          }

      - name: Update index.html
        run: |
          $content = Get-Content -Path index.html
          $newContent = $content -replace "https://{{NGROK_ADDRESS}}", "${{ steps.get-address.outputs.ngrok_url }}"
          $newContent | Set-Content -Path index.html

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.html
          if (-not (git diff --quiet)) {
            git commit -m "Update ngrok address in index.html to ${{ steps.get-address.outputs.ngrok_url }}"
            git push
          } else {
            echo "No changes to commit"
          }    
